config/routes.rb
Rails.application.routes.draw do
    resources :products
    root 'top#main'
    get 'top/main'
    resources :cartitems, only: [:new, :create, :destroy]
    resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class Cartitem < ApplicationRecord
    validates :qty, numericality: {only_integer: true, greater_than_or_equal_to: 0}
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cartitems, dependent: :destroy
    
    validates :name, :price, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_cart
            if session[:cart_id]
                cart = Cart.find(session[:cart_id])
            else
                cart = Cart.create
                session[:cart_id] = cart.id
            end
            cart
        end
        helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartitemsController < ApplicationController
    def new
        @cartitem = Cartitem.new(product_id: params[:product_id])
    end
    
    def create
        @cartitem = Cartitem.new(product_id: params[:cartitem][:product_id], cart_id: current_cart.id,
        qty: params[:cartitem][:qty])
        if @cartitem.save
            flash[:notice] = 'カートに商品を追加しました。'
            redirect_to root_path
        else
            render new_cartitem_path
        end
    end
    
    def destroy
        @cartitem = Cartitem.find(params[:id])
        @cartitem.destroy
        flash[:notice] = 'カートから商品を削除しました。'
        render 'carts/show'
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart = Cart.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(name: params[:product][:name],  price: params[:product][:price])
        if @product.save
            redirect_to root_path
        else
            render new_product_path
        end
    end
    
    def destroy
        product = Product.find(params[:id])
        product.destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        redirect_to products_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart_items/new.html.erb
<% if @cartitem.errors.present? %>
    <p>エラーがあります。</p>
    <ul>
        <% @cartitem.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @cartitem , url: {action: :create} do |f| %>
    <p>
        商品名：<%= Product.find(@cartitem.product_id).name %>
    </p>
    <p>
        価格：<%= Product.find(@cartitem.product_id).price %>
    </p>
    <p>
        <%= f.label :qty, '数量' %>
        <%= f.text_field :qty %>
    </p>
    <%= f.hidden_field :product_id %>
    <%= f.submit '商品を登録する' %>
<% end %>

<br><%= link_to '商品一覧に戻る', products_path %>

app/views/carts/show.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

<% items = Cartitem.where(cart_id: current_cart.id) %>
<% sum = 0 %>
<% items.each do|item| %>
    <% product = Product.find(item.product_id) %>
    <p>
        <%= product.name %>
        <%= product.price %>円
        数量：<%= item.qty %>
        <%= link_to 'カートから削除', cartitem_path(item.id), method: :delete %>
    </p>
    <% sum += ((product.price).to_i * (item.qty).to_i) %>
<% end %>
<p>
    合計金額：<%= sum %>円
</p>

<%= link_to '商品一覧に戻る', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

<% @products.each do |product| %>
<p>
    <%= product.name%>
    <%= product.price%>円
    <%= link_to '削除', product_path(product) ,method: :delete %>
    <%= link_to 'カートに追加', new_cartitem_path(product_id: product.id) %>
</p>
<% end %>

<%= link_to '商品を追加する', new_product_path %><br>
<%= link_to 'カートを見る', cart_path(current_cart.id) %>

app/views/products/new.html.erb
<% if @product.errors.present? %>
    <p>エラーがあります。</p>
    <ul>
        <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @product , url: {action: :create} do |f| %>
    <p>
        <%= f.label :name, '商品名' %>
        <%= f.text_field :name %>
        <%= f.label :price, '価格' %>
        <%= f.text_field :price %>
        <%= f.submit '登録' %>
    </p>
<% end %>

<br><%= link_to '商品一覧に戻る', products_path %>